"""Convert the Hershey Sans 1-stroke SVG font into a C header of line segments.

Usage: python gen_stroke_font.py > ../../client/src/stroke_font.h
Source: hersheytext npm package 2.0.0 (svg_fonts/HersheySans1.svg).
"""
import re

svg = open("HersheySans1.svg", encoding="utf-8").read()
UNITS = 1000.0  # font units per em in this file (cap height ~662)

glyphs = {}
for m in re.finditer(r'<glyph unicode="([^"]*)"[^>]*?horiz-adv-x="([\d.]+)"(?:[^>]*?d="([^"]*)")?', svg):
    ch, adv, d = m.group(1), float(m.group(2)), m.group(3) or ""
    ch = {"&amp;": "&", "&lt;": "<", "&gt;": ">", "&quot;": '"', "&apos;": "'"}.get(ch, ch)
    if len(ch) != 1 or not (32 <= ord(ch) <= 126):
        continue
    segs = []
    pen = None
    for cmd, x, y in re.findall(r"([ML])\s*(-?[\d.]+)\s+(-?[\d.]+)", d):
        p = (float(x) / UNITS, float(y) / UNITS)
        if cmd == "L" and pen is not None:
            segs.append((pen, p))
        pen = p
    glyphs[ord(ch)] = (adv / UNITS, segs)

print("""// Generated by tools/fontgen/gen_stroke_font.py from Hershey Sans 1-stroke
// (hersheytext 2.0.0, svg_fonts/HersheySans1.svg).
//
// The Hershey Fonts were originally created by Dr. A. V. Hershey while working at
// the U. S. National Bureau of Standards.
// The format of the Font data in this distribution was originally created by
// James Hurt, Cognition, Inc., 900 Technology Park Drive, Billerica, MA 01821.
//
// Units: em (cap height ~0.66). Each glyph is a list of line segments.
#pragma once
#include <stdint.h>

struct StrokeGlyph {
    float advance;
    uint16_t first; // index into stroke_font_segs
    uint16_t count;
};
""")
segs_all = []
table = []
for c in range(32, 127):
    adv, segs = glyphs.get(c, (0.5, []))
    table.append((adv, len(segs_all), len(segs)))
    segs_all.extend(segs)
print("static const float stroke_font_segs[][4] = {")
for (a, b) in segs_all:
    print("    {%.4ff, %.4ff, %.4ff, %.4ff}," % (a[0], a[1], b[0], b[1]))
print("};")
print("static const StrokeGlyph stroke_font_glyphs[95] = {")
for adv, first, count in table:
    print("    {%.4ff, %d, %d}," % (adv, first, count))
print("};")
