"""Render printable ASCII from DejaVu Sans Mono into a 1-bpp C header.

Usage: python gen_font.py > ../../client/src/font_data.h
"""
from PIL import Image, ImageDraw, ImageFont

W, H = 12, 24
font = ImageFont.truetype("DejaVuSansMono.ttf", 20)
ascent, _ = font.getmetrics()

print("// Generated by tools/fontgen/gen_font.py from DejaVu Sans Mono (Bitstream Vera license).")
print("#pragma once")
print("#include <stdint.h>")
print(f"#define FONT_W {W}")
print(f"#define FONT_H {H}")
print("#define FONT_FIRST 32")
print("#define FONT_LAST 126")
print(f"static const uint16_t font_data[95][{H}] = {{")
for c in range(32, 127):
    img = Image.new("L", (W, H), 0)
    ImageDraw.Draw(img).text((0, 19 - ascent), chr(c), font=font, fill=255)
    rows = []
    for y in range(H):
        bits = 0
        for x in range(W):
            if img.getpixel((x, y)) > 110:
                bits |= 1 << (W - 1 - x)
        rows.append(f"0x{bits:03x}")
    print("  {" + ",".join(rows) + "},")
print("};")
